application: counter-attack-football
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /styles
  static_dir: static/styles

- url: /images
  static_dir: static/images
  
- url: /jsfiles
  static_dir: static/jsfiles
 
- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest